### ISSUE TITLE
Matrix4.at() and a few other functions do not work

### ISSUE THREAD

**Issue by dasMalle** [OniDaito/CoffeeGL#6]
Hey :) 
we discovered that even though Matrix3.at() works perfectly Matrix4.at doesn't... 
Have you seen that before? Could it be a scoping issue in our project? 
If not any idea what causes it and should we fix it and create a pull request? 
Nice library btw, your code is pretty easy to read!

**Comment by OniDaito** [comment]
Oh interesting. If you have a fix, do submit a pull request. I've come back to this library recently so there have been changes (including automagic shaders). But yes, whoever gets there first! thanks for the kind words. I'm going to rebrand this library so it has a shorter name in the near future - lots of things planned.

**Comment by OniDaito** [comment]
The latest commit should fix this. A rather embarrassing mistake to make. Thanks for spotting it :)
