### ISSUE TITLE
RequestAnimationFrame functionality chooses deprecated function (in Chrome at least)

### ISSUE THREAD

**Issue by derrelldurrett** [OniDaito/CoffeeGL#7]
Running coffeegl in Chrome (43.0.2357.124 m on Windows 7) results in a deprecation warning: ```'webkitRequestAnimationFrame' is vendor-specific. Please use the standard 'requestAnimationFrame' instead.```

Maybe check for that one first now?

**Comment by OniDaito** [comment]
Yeah, I've noticed that too, thanks :) Should be an easy win. Will look at that, at the weekend.

**Comment by OniDaito** [comment]
This has now been fixed.
